wave_application/Models/OfEncours.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace wave_application.Models
{
    public class OfEncours
    {
        [Key]
        public int Id { get; set; }

        [Display(Name = "N° OF Composant")]
        public int OfComposant { get; set; }

        [Display(Name = "N° Carton Composant ")]
        public int CartonComposant { get; set; }

        [Display(Name = "N° Trémie")]
        public string Tremie { get; set; }

        [Display(Name = "N° OF Assemblage")]
        public int OfAssemblage { get; set; }

        [Display(Name = "N° Article Assemblage")]
        public int ArticleAssemblage { get; set; }
        public DateTime Date { get; set; }

        [Display(Name = "Code Opérateur")]
        public string Operateur { get; set; }
    }
}

wave_application/Controllers/OfEncoursController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using wave_application.Datas;
using wave_application.Models;
using iTextSharp.text.pdf;
using iTextSharp.text;
using JsonSerializer = System.Text.Json.JsonSerializer;
using System.Printing;
using Org.BouncyCastle.Crypto.Tls;
//using Font = System.Drawing.Font;
using Microsoft.AspNetCore.Http.Features;
using System.Net;
using System.IO;

namespace wave_application.Controllers
{
    public class OfEncoursController : Controller
    {
        private readonly DefaultContext _context;

        public OfEncoursController(DefaultContext context)
        {
            _context = context;
        }

        /**
         * Méthode qui permet de lister les cartons utilisés dans les trémies
         */
        public IActionResult Index(int page = 1, int pageSize = 10)
        {
            List<OfEncours> ofEncours = _context.OfEncours.OrderByDescending(e => e.Date).ToList();
            var count = ofEncours.Count;
            var items = ofEncours.Skip((page - 1) * pageSize).Take(pageSize).ToList();

            ViewBag.PageNumber = page;
            ViewBag.PageSize = pageSize;
            ViewBag.TotalPages = (int)Math.Ceiling((double)count / pageSize);
            ViewBag.HasPreviousPage = (page > 1);
            ViewBag.HasNextPage = (page < ViewBag.TotalPages);
            return View(items);
        }

        [HttpGet]
        public IActionResult Edit(int Id)
        {
            OfEncours encours = _context.OfEncours.Where(o => o.Id == Id).FirstOrDefault();
            return View(encours);
        }

        
        /**
         * Modifier les informations sur un carton utilisé dans la trémie
         */
        [HttpPost]
        public IActionResult Edit(OfEncours encours)
        {
            _context.Attach(encours);
            _context.Entry(encours).State = EntityState.Modified;
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        /**
         * Méthode qui permet d'afficher le résultat de la recherche 
         */
        [HttpPost]

        public IActionResult ReplaceData(IFormCollection form)
        {
            var search = form["mot"];
            var dateStart = form["dateDebut"];
            var dateEnd = form["dateFin"];

            DateTime? start = DateTime.TryParse(dateStart, out DateTime parsedDate) ? parsedDate : DateTime.MinValue;
            DateTime? end = DateTime.TryParse(dateEnd, out DateTime parsedDate2) ? parsedDate2 : DateTime.MinValue;

            List<OfEncours> data = new();

            // Si on a une date de début et pas de date de fin, on renvoie les éléments de la date de début
            if (string.IsNullOrEmpty(search) && start != DateTime.MinValue && end == DateTime.MinValue)
            {
                data = _context.OfEncours.Where(item => item.Date.Date == start).OrderByDescending(e => e.Date).ToList();
            }
            // Si on a une date de début et une date de fin, on renvoie les éléments entre les deux dates
            else if (string.IsNullOrEmpty(search) && start != DateTime.MinValue && end != DateTime.MinValue)
            {
                data = _context.OfEncours.Where(item => item.Date.Date >= start && item.Date.Date <= end).OrderByDescending(e => e.Date).ToList();
            }
            // Si on a un mot et pas de date, on renvoie les éléments contenant le mot
            else if (!string.IsNullOrEmpty(search) && start == DateTime.MinValue && end == DateTime.MinValue)
            {
                data = _context.OfEncours.Where(item => item.OfComposant == int.Parse(search) || item.ArticleAssemblage == int.Parse(search) || item.OfAssemblage == int.Parse(search)).OrderByDescending(e => e.Date).ToList();
            }
            // Si on a un mot, une date de début et pas de date de fin, on renvoie les éléments contenant le mot et de la date de début
            else if (!string.IsNullOrEmpty(search) && start != DateTime.MinValue && end == DateTime.MinValue)
            {
                data = _context.OfEncours.Where(item => item.OfComposant == int.Parse(search) && item.Date.Date == start || item.ArticleAssemblage == int.Parse(search) 
                && item.Date.Date == start || item.OfAssemblage == int.Parse(search) && item.Date.Date == start).OrderByDescending(e => e.Date).ToList();
            }
            // Si on a un mot, une date de début et une date de fin, on renvoie les éléments contenant le mot et entre les deux dates
            else if (!string.IsNullOrEmpty(search) && start != DateTime.MinValue && end != DateTime.MinValue)
            {
                data = _context.OfEncours.Where(item => item.OfComposant == int.Parse(search) && item.Date.Date >= start && item.Date.Date <= end || item.ArticleAssemblage == int.Parse(search)
                && item.Date.Date >= start && item.Date.Date <= end || item.OfAssemblage == int.Parse(search) && item.Date.Date >= start && item.Date.Date <= end).OrderByDescending(e => e.Date).ToList();
            }
            else
            {
                TempData["AlertMessage"] = " les champs sont vides";
                return RedirectToAction("Index");
            }


            var json = JsonSerializer.Serialize(data);
            HttpContext.Session.SetString("liste", json);

            return View("ListeFiltre", data);
        }
      
        /**
         * Méthode qui permet de télécharger le PDF
         */
        public ActionResult TelechargerPdf()
        {
            string json = HttpContext.Session.GetString("liste");
            List<OfEncours> data = JsonSerializer.Deserialize<List<OfEncours>>(json);
            string chemin = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.UserProfile), "Downloads", "liste.pdf");
            // Créer un document PDF
            Document document = new(PageSize.A4.Rotate(), 10f, 10f, 10f, 0f);

            // Créer un objet PdfWriter pour écrire le contenu du document PDF
            _ = PdfWriter.GetInstance(document, new FileStream(chemin, FileMode.Create));
            document.Open();

            var font = FontFactory.GetFont("Arial", 16);
            var paragraph = new Paragraph("Historique des cartons", font)
            {
                SpacingBefore = 20f,
                SpacingAfter = 10f
            };
            document.Add(paragraph);

            // Créer un tableau avec 8 colonnes
            PdfPTable table = new(7)
            {
                WidthPercentage = 100
            };
            table.AddCell("N° Composant");
            table.AddCell("N° Carton");
            table.AddCell("N° Trémie");
            table.AddCell("N° OF Assemblage");
            table.AddCell("N° Article Assemblage");
            table.AddCell("Opérateur");
            table.AddCell("Date");

            foreach (var item in data)
            {
                table.AddCell(item.OfComposant.ToString());
                table.AddCell(item.CartonComposant.ToString());
                table.AddCell(item.Tremie);
                table.AddCell(item.OfAssemblage.ToString());
                table.AddCell(item.ArticleAssemblage.ToString());
                table.AddCell(item.Operateur);
                table.AddCell(item.Date.ToString());
            }
            // Ajouter le tableau au document
            document.Add(table);
            document.Close();
            TempData["AlertSuccess"] = " Fichier téléchargé avec le nom liste...";
            return View("ListeFiltre", data);
        }
    } 
}

wave_application/Views/OfEncours/Edit.cshtml
@model wave_application.Models.OfEncours

@{
    ViewData["Title"] = "Modification";
}

<h1>Modification de l'OF encours d'utilisation</h1>

<hr />
<div class="row" id="formulaireS">
    <div class="col-md-6">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="OfComposant" class="control-label"></label>
                <input asp-for="OfComposant" class="form-control" />
                <span asp-validation-for="OfComposant" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CartonComposant" class="control-label"></label>
                <input asp-for="CartonComposant" class="form-control" />
                <span asp-validation-for="CartonComposant" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tremie" class="control-label"></label>
                <input asp-for="Tremie" class="form-control" />
                <span asp-validation-for="Tremie" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OfAssemblage" class="control-label"></label>
                <input asp-for="OfAssemblage" class="form-control" />
                <span asp-validation-for="OfAssemblage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ArticleAssemblage" class="control-label"></label>
                <input asp-for="ArticleAssemblage" class="form-control" />
                <span asp-validation-for="ArticleAssemblage" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input asp-for="Operateur" class="form-control" hidden/>
                <input asp-for="Date" class="form-control" hidden />
            </div>
          
            <div id="buttonForm">
                <a class="btn btn-primary" asp-action="Index">Retour</a>
                <input type="submit" value="Valider" class="btn btn-primary" /> 
            </div>
        </form>
    </div>
    
</div>

wave_application/Views/OfEncours/Index.cshtml
@model IEnumerable<wave_application.Models.OfEncours>

@{
    ViewData["Title"] = "Suivi OF";
}

<h1>Historique des Composants  pour l'assemblage</h1>

<p>
    <a class="btn btn-primary" asp-controller="Home" asp-action="Index">Retour</a>
    <a id="filtre" class="btn btn-primary" data-toggle="modal" data-target="@("#ModalDate")">Filtre</a>
</p>
<div class="table-responsive" id="table">
    <table class="table table-bordered table-striped">
    <thead class="text-center">
        <tr>
            <th>
               N° Composant
            </th>
            <th>
                N° Carton
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tremie)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OfAssemblage)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ArticleAssemblage)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Operateur)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            
            <th>Modifier</th>
        </tr>
    </thead>
    <tbody class="text-center">
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.OfComposant)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CartonComposant)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Tremie)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OfAssemblage)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ArticleAssemblage)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Operateur)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
           
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-primary">Modifier</a>
            </td>
        </tr>
}
    </tbody>
</table>
</div>
<!--  ____________________________________PAGINATION_____________________________________________ -->
<div id="paginator" class="btn-group">
    @if (ViewBag.HasPreviousPage)
    {
        <a href="@Url.Action("Index", new { page = ViewBag.PageNumber - 1, pageSize = ViewBag.PageSize })" class="page-link">Précédent</a>
    }

    @if (ViewBag.PageNumber > 1)
    {
        <a href="@Url.Action("Index", new { page = 1, pageSize = ViewBag.PageSize })" class="page-link">1</a>
    }

    @if (ViewBag.PageNumber > 5)
    {
        <span class="ellipsis">...</span>
    }

    @for (int i = Math.Max(1, ViewBag.PageNumber - 3); i <= Math.Min(ViewBag.PageNumber + 3, ViewBag.TotalPages); i++)
    {
        if (i != 1 && i != ViewBag.TotalPages)
        {
            if (i == ViewBag.PageNumber)
            {
                <span class="page-link current">@i</span>
            }
            else
            {
                <a href="@Url.Action("Index", new { page = i, pageSize = ViewBag.PageSize })" class="page-link">@i</a>
            }
        }
    }

    @if (ViewBag.PageNumber < ViewBag.TotalPages - 4)
    {
        <span class="ellipsis">...</span>
    }

    @if (ViewBag.PageNumber < ViewBag.TotalPages)
    {
        <a href="@Url.Action("Index", new { page = ViewBag.TotalPages, pageSize = ViewBag.PageSize })" class="page-link">@ViewBag.TotalPages</a>
    }

    @if (ViewBag.HasNextPage)
    {
        <a href="@Url.Action("Index", new { page = ViewBag.PageNumber + 1, pageSize = ViewBag.PageSize })" class="page-link">Suivant</a>
    }
</div>

<!--  ___________________________________FIN PAGINATION_______________________________________________________________________ -->
@await Html.PartialAsync("ModalDate")

wave_application/Views/OfEncours/ListeFiltre.cshtml
@model IEnumerable<wave_application.Models.OfEncours>

@{
    ViewData["Title"] = "Suivi OF";
}
@if (TempData["AlertSuccess"] != null)
{
    <div class="alert alert-success">
        <strong>Succès : </strong>@TempData["AlertSuccess"]
    </div>
}
<h1>Historique des composants utilisés </h1>

<p>
    <a class="btn btn-primary"  asp-action="Index">Retour</a>
    @if (Model != null && Model.Count() > 0)
    {
        <a href="@Url.Action("TelechargerPdf", "OfEncours")"> <img src="~/img/document-pdf.svg" id="pdf" /></a>
    }
</p>
@if (Model != null && Model.Count() > 0)
{
    <table class="table table-bordered table-striped">
        <thead class="text-center">
            <tr>
                <th>
                    N° Composant
                </th>
                <th>
                    N° Carton
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Tremie)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.OfAssemblage)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ArticleAssemblage)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Operateur)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Date)
                </th>

                <th>Modifier</th>
            </tr>
        </thead>
        <tbody class="text-center">
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.OfComposant)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CartonComposant)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Tremie)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.OfAssemblage)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ArticleAssemblage)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Operateur)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Date)
                    </td>

                    <td>
                        <a asp-action="Edit" asp-route-id="@item.Id">Modifier</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <h1> La liste est vide</h1>
}

wave_application/Views/OfEncours/ModalDate.cshtml
<!-- Modal -->
<div class="modal fade" id="ModalDate" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title" id="exampleModalLabel">Remplir les champs</h3>
                   
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span> 
                </button>
            </div>
           
            <div class="modal-body">
                <form method="post" action="@Url.Action("ReplaceData", "OfEncours")">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label class="control-label">N° OF ou Article</label>
                        <input class="form-control" name="mot"/>
                    </div>

                    <div class="form-group">
                        <label  class="control-label">Début date</label>
                        <input type="date" class="form-control" name="dateDebut"/>
                    </div>

                    <div class="form-group">
                        <label class="control-label">Fin date</label>
                        <input type="date" class="form-control" name="dateFin" />
                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer</button>
                        <input type="submit" value="Valider" class="btn btn-primary"/>
                    </div>
                </form>
            </div>

        </div>
    </div>
</div>