wave_application/Models/Imprimante.cs
using System.ComponentModel.DataAnnotations;

namespace wave_application.Models
{
    public class Imprimante
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "Ce champ est obligatoire")]
        [Display(Name = "Nom PC")]
        public string NomPc { get; set; }

        [Required(ErrorMessage = "Ce champ est obligatoire")]
        [Display(Name = "Nom Imprimante")]
        public string NomImprimante { get; set; }
    }
}

wave_application/Controllers/ImprimanteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using wave_application.Datas;
using wave_application.Models;

namespace wave_application.Controllers
{
    public class ImprimanteController : Controller
    {
        private readonly DefaultContext _context;

        public ImprimanteController(DefaultContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
              return View(await _context.Imprimantes.ToListAsync());
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,NomPc,NomImprimante")] Imprimante imprimante)
        {
            if (ModelState.IsValid)
            {
                _context.Add(imprimante);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(imprimante);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Imprimantes == null)
            {
                return NotFound();
            }

            var imprimante = await _context.Imprimantes.FindAsync(id);
            if (imprimante == null)
            {
                return NotFound();
            }
            return View(imprimante);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,NomPc,NomImprimante")] Imprimante imprimante)
        {
            if (id != imprimante.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(imprimante);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ImprimanteExists(imprimante.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(imprimante);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Imprimantes == null)
            {
                return NotFound();
            }

            var imprimante = await _context.Imprimantes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (imprimante == null)
            {
                return NotFound();
            }

            return View(imprimante);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Imprimantes == null)
            {
                return Problem("Entity set 'DefaultContext.Imprimantes'  is null.");
            }
            var imprimante = await _context.Imprimantes.FindAsync(id);
            if (imprimante != null)
            {
                _context.Imprimantes.Remove(imprimante);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ImprimanteExists(int id)
        {
          return _context.Imprimantes.Any(e => e.Id == id);
        }
    }
}

wave_application/Views/Imprimante/Create.cshtml
@model wave_application.Models.Imprimante

@{
    ViewData["Title"] = "Create";
}

<h1>Associer une Imprimante à un PC</h1>

<hr />
<div class="row" id="formulaireS">
    <div class="col-md-6">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NomPc" class="control-label"></label>
                <input asp-for="NomPc" class="form-control" />
                <span asp-validation-for="NomPc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NomImprimante" class="control-label"></label>
                <input asp-for="NomImprimante" class="form-control" />
                <span asp-validation-for="NomImprimante" class="text-danger"></span>
            </div>
            <div id="buttonForm">
                <a class="btn btn-primary" asp-asp-controller="Imprimante" asp-action="Index">Retour</a>
                <input type="submit" value="Valider" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

wave_application/Views/Imprimante/Delete.cshtml
@model wave_application.Models.Imprimante

@{
    ViewData["Title"] = "Delete";
}

<h1>Êtes-vous sûr de vouloir supprimer ceci ?</h1>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NomPc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NomPc)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NomImprimante)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NomImprimante)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <a asp-action="Index" class="btn btn-primary">Retour</a> |
        <input type="submit" value="Supprimer" class="btn btn-danger" />
    </form>
</div>

wave_application/Views/Imprimante/Edit.cshtml
@model wave_application.Models.Imprimante

@{
    ViewData["Title"] = "Modification";
}

<h1>Modification </h1>

<hr />
<div class="row" id="formulaireS">
    <div class="col-md-6">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="NomPc" class="control-label"></label>
                <input asp-for="NomPc" class="form-control" />
                <span asp-validation-for="NomPc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NomImprimante" class="control-label"></label>
                <input asp-for="NomImprimante" class="form-control" />
                <span asp-validation-for="NomImprimante" class="text-danger"></span>
            </div>
             <div id="buttonForm">
                <a class="btn btn-primary" asp-asp-controller="Imprimante" asp-action="Index">Retour</a>
                <input type="submit" value="Valider" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

wave_application/Views/Imprimante/Index.cshtml
@model IEnumerable<wave_application.Models.Imprimante>

@{
    ViewData["Title"] = "Index";
}

<h1>Liste des Ordinateurs avec l'imprimantes associées </h1>

<p>
    <a class="btn btn-primary" asp-controller="Home" asp-action="Index">Retour</a>
    <a class="btn btn-primary" asp-action="Create">Nouveau</a>
</p>
<table class="table table-bordered table-striped">
    <thead class="text-center">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NomPc)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NomImprimante)
            </th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody class="text-center">
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NomPc)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NomImprimante)
            </td>
            <td>
                <a class="btn btn-primary" asp-action="Edit" asp-route-id="@item.Id">Modifier</a> |
                <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.Id">Supprimer</a>
            </td>
        </tr>
}
    </tbody>
</table>