wave_application/Models/Injection.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace wave_application.Models
{
    public class Injection
    {
        [Key]
        public int Id { get; set; }

        [Display(Name = "N° OF")]
        public int Of { get; set; }

        [Display(Name = "N° Article")]
        public int Article { get; set; }

        [Display(Name = "N° Carton")]
        public int Carton { get; set; }
        public DateTime Date { get; set; }

        [Display(Name = "N° Palette")]
        public int Palette { get; set; }

        [Display(Name = "Quantité")]
        public int Quantite { get; set; }

        [Display(Name = "Fin Palette")]
        public Boolean FinPalette { get; set; }

        [Display(Name = "Code Opérateur")]
        public String Operateur { get; set; }
        public string Emplacement { get; set; }
        public Boolean Bloquer { get; set; }
        public Boolean Supprimer { get; set; }
        public int Delai { get; set; }
        public string Libelle { get; set; }
    }

}

wave_application/Controllers/InjectionController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Drawing.Printing;
using System.IO;
using System.Linq;
using wave_application.Datas;
using wave_application.Models;
using iTextSharp.text;
using iTextSharp.text.pdf;
using JsonSerializer = System.Text.Json.JsonSerializer;
using Microsoft.AspNetCore.Http.Features;
using System.Net;
using Newtonsoft.Json;
using System.Drawing;
using Font = System.Drawing.Font;
using System.Drawing.Imaging;
using static iTextSharp.text.pdf.AcroFields;
using System.Threading.Tasks;
using System.Windows.Markup;
using System.Text;
using System.Windows;
using System.Printing;
using System.Linq.Expressions;

namespace wave_application.Controllers
{
    public class InjectionController : Controller
    {
        private readonly DefaultContext _context;

        public InjectionController(DefaultContext context, DefaultContext dbContext)
        {
            _context = context;
        }

        /**
         * Méthode pour afficher l'ensemeble des injection
         * qui ne sont pas supprimées
         */
        public IActionResult Index(int page = 1, int pageSize = 10)
        {
            List<Injection> injections = _context.Injections.Where(i => i.Supprimer == false).OrderByDescending(e => e.Date).ToList();
            var count = injections.Count;
            var items = injections.Skip((page - 1) * pageSize).Take(pageSize).ToList();

            ViewBag.PageNumber = page;
            ViewBag.PageSize = pageSize;
            ViewBag.TotalPages = (int)Math.Ceiling((double)count / pageSize);
            ViewBag.HasPreviousPage = (page > 1);
            ViewBag.HasNextPage = (page < ViewBag.TotalPages);
            return View(items);
        }

        /*
         * Méthode pour afficher la page avec le formulaire de création de l'injection
         * 
         */
        [HttpGet]
        public IActionResult Create()
        {
            var userJson = HttpContext.Session.GetString("user");
            var user = JsonConvert.DeserializeObject<User>(userJson);
            var ofJson = HttpContext.Session.GetString("of");
            ViewBag.affichage = TempData["affichage"] as string;

            if (userJson != null)
            {
                ViewData["User"] = user.Code;
                if (!string.IsNullOrEmpty(ofJson))
                {
                    var of = JsonConvert.DeserializeObject<Injection>(ofJson);
                    return View(of);
                }  
            }
            else
            {
                ViewData["User"] = user.Code;
            }
            return View();
        }


        /*
         * Méthode qui traite le formulaire de création de l'injection
         */
        [HttpPost]
        public IActionResult Create(Injection injection, string action)
        {
            List<TArticle> listeArticle = _context.TArticles.Where(a => a.CodeJDE == injection.Article).ToList();
            injection.Date = DateTime.Now;
           

            VerifyInjection(injection, listeArticle, action); // Méthode pour vérifier le N° Article, finPalette et l'incrémentation de carton + palette

            if (TempData.ContainsKey("AlertMessage") && TempData["AlertMessage"].ToString() == "Numéro d'article inconnu...")
            {
                return RedirectToAction("Verify", "Verify");
            }

            //Création du fichier temporaire pour l'impresion
            string old = injection.Of + injection.Article + ".txt";
            string chemin = "\\\\A576FR10\\Download$\\";
            string fullPath = Path.Combine(chemin, old);
            System.IO.File.Create(fullPath).Dispose();

            ReplaceTextInFile(injection, listeArticle, fullPath); // méthode pour remplir le ficher
            
            try
            {
                // Verfication sur la quantité de carton à produire 
                CartonJDE cartonJDE = _context.CartonJDE.FirstOrDefault(c => c.NumArticle == injection.Article);
                string stage = TempData["Etape"] as string;

                if (stage == null)
                {

                    if (cartonJDE != null)
                    {
                        if (injection.FinPalette)
                        {
                            if (cartonJDE.CartonPalette == injection.Carton)
                            {
                                TempData["AlertSuccess"] = cartonJDE.CartonPalette == 1
                                ? "Big Bag enregistré avec une fin de palette"
                                : "Le Contenant est enregistré avec une fin de palette ";
                            }
                            else if (injection.Carton < cartonJDE.CartonPalette || injection.Carton > cartonJDE.CartonPalette)
                            {
                                TempData["AlertSuccess"] = "Le Contenant est enregistré avec une fin de palette ";
                            }
                        }
                        else
                        {
                            if (cartonJDE.CartonPalette == injection.Carton)
                            {
                                if (cartonJDE.CartonPalette == 1)
                                {
                                    injection.FinPalette = true;
                                    injection.Emplacement = "E";
                                    TempData["AlertSuccess"] = "Big Bag enregistré avec une fin de palette";
                                }
                                else
                                {
                                    stage = "ModalConfirmation";
                                }
                            }
                            else if (injection.Carton < cartonJDE.CartonPalette)
                            {
                                TempData["AlertSuccess"] = " Le contenant est enregistré et vous êtes sur le N° " + injection.Carton;
                            }
                            else if (injection.Carton > cartonJDE.CartonPalette)
                            {
                                stage = "ModalConfirmation";
                            }
                        }
                    }
                    else
                    {
                        TempData["AlertMessage"] = "Numéro d'article inconnu...";
                        return RedirectToAction("Verify", "Verify");
                    }
                }

                switch (stage)
                {
                    case "ModalConfirmation":
                        return RedirectToAction("ModalConfirmation");
                    case "OK":
                        TempData["Etape"] = null;
                        injection.FinPalette = true;
                        injection.Emplacement = "E";
                        List<Injection> liste = _context.Injections.Where(e => e.Of == injection.Of && e.Palette == injection.Palette).ToList();
                        liste.ForEach(e => e.Emplacement = "E");
                        TempData["AlertSuccess"] = "Le contant est enregistré avec une fin de palette";
                        break;
                    case "NonOK":
                        TempData["Etape"] = null;
                        TempData["AlertSuccess"] = " Le contenant est enregistré et vous êtes sur le N° " + injection.Carton;
                        break;
                    case "Annuler":
                        TempData["Etape"] = null;
                        return RedirectToAction("Verify", "Verify");
                }

                _context.Attach(injection);
                _context.Entry(injection).State = EntityState.Added;
                _context.SaveChanges();

                PrintToServer(fullPath); // Récupération des informations sur le serveur et lancer l'impression
                System.IO.File.Delete(fullPath); // Supprimer le fichier 
                HttpContext.Session.Remove("of"); // Vider la session

                return RedirectToAction("Verify", "Verify");
            }
            catch (Exception e)
            {
                System.IO.File.Delete(fullPath);
                var file = "debug.txt";
                string pathServer = "\\\\A576FR10\\Download$\\";
                string file_path = Path.Combine(pathServer, file);
                System.IO.File.WriteAllText(file_path, e.Message);
                TempData["AlertMessage"] = "Erreur lors de l'enregistrement... ";
                TempData["AlertSuccess"] = null;
            }            

            return RedirectToAction("Verify", "Verify");
        }


        /************************************TRAITEMENT POUR LA BOITE DE DIALOGUE POUR LES FIN DE PALETTE ET LES REQUETES INJECTIONS ******************************/

        public void VerifyInjection(Injection injection, List<TArticle> listeArticle, string action)
        {
            List<Injection> injections = _context.Injections.Where(i => i.Supprimer == false).ToList();
            var query = _context.Injections.Where(i => i.Of == injection.Of && i.Supprimer == false).ToList();
            if (listeArticle.Count != 0)
            {
                var article = listeArticle.FirstOrDefault().Libelle2;
                var time = _context.Delais.FirstOrDefault(d => d.Libelle == article);
                injection.Delai = time?.Delais ?? 24;
                injection.Libelle = article;

                if (injections.Count == 0)
                {
                    injection.Carton = 1;
                    injection.Palette = 1;
                }
                else if (query.Count != 0 && query.Last().FinPalette == false)
                {
                    injection.Palette = query.Last().Palette;
                    injection.Carton = query.Last().Carton + 1;
                }
                else if (query.Count != 0 && query.Last().FinPalette)

wave_application/Views/Injection/Create.cshtml
@model wave_application.Models.Injection

@{
    ViewData["Title"] = "Composant";
}
@if (ViewBag.ShowDialog == true)
{
    <div id="dialog" title="Boîte de dialogue">
        <p>Voulez-vous appliquer une Fin de palette @ViewBag.Action ?</p>
    </div>
}
<h1>Déclaration du composant et Impression de l'étiquette</h1>

<hr />

<div class="row" id="formulaireS">
    <div class="col-md-6">
        @using (Html.BeginForm("Create", "Injection", FormMethod.Post))
        {
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group"> 
                <label asp-for="Of" class="control-label"></label>
                <input asp-for="Of" class="form-control" id="of" autocomplete="off" />
                <span asp-validation-for="Of" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Article" class="control-label">N° Article JDE</label>
                <input asp-for="Article" class="form-control" min="0" required autocomplete="off" />
                <span asp-validation-for="Article" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantite" class="control-label">Quantité par contenant</label>
                <input asp-for="Quantite" class="form-control" min="0" />
                <span asp-validation-for="Quantite" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Carton" class="control-label"></label>
                <input asp-for="Carton" class="form-control" hidden />
                <input class="form-control" value="Valeur automatique" disabled="disabled" />
                <span asp-validation-for="Carton" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Operateur" class="control-label"></label>
                <input asp-for="Operateur" class="form-control" id="operateur" hidden value="@ViewData["User"]" />
                <input asp-for="Operateur" class="form-control" disabled="disabled" value="@ViewData["User"]" />
                <span asp-validation-for="Operateur" class="text-danger"></span>
            </div>
            <div id="buttonForm">
                <a class="btn btn-primary" href="/">Retour</a>
                <button type="submit" name="action" value="Creation" class="btn btn-primary">Impression + Validation</button>
                <button type="submit" name="action" value="FinPalette" class="btn btn-primary">FinPalette + Validation</button>
            </div>

            
            <div id="loadingIndicator" style="display: none;">
                <i class="fa fa-spinner fa-spin"></i> Traitement en cours...
            </div>
            
            
       }
    </div>
</div>

@section Scripts {
    <script>
        var strValue = "@((string)ViewBag.mssg)";
        if (strValue !== null && strValue !== '') {
            swal("Le code opérateur invalide désolé", "", "error");
        }

        // Vérifier si la variable existe et soumettre le formulaire
        $(document).ready(function () {
            var maVariable = "@((string)ViewBag.affichage)";
            if (maVariable) {
                $('form').submit();
            }
        });
    </script>
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

wave_application/Views/Injection/Delete.cshtml
@model wave_application.Models.Injection

@{
    ViewData["Title"] = "Delete";
}

<h1>Êtes-vous sûr de vouloir supprimer ceci ? </h1>
@if (TempData["AlertMessage"] != null)
{
    <div class="alert alert-danger">
        <strong>Erreur : </strong>@TempData["AlertMessage"]
    </div>
}
<hr />
<div class="row" id="formulaireS">
    <div class="col-md-6">
        <form asp-action="Delete">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Of" class="control-label"></label>
                <input asp-for="Of" class="form-control" />
                <input class="form-control" hidden id="ofInjection" value="@Model.Of" name="ofInjection" />
                <span asp-validation-for="Of" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Article" class="control-label"></label>
                <input asp-for="Article" class="form-control" />
                <input class="form-control" hidden id="articleInjection" value="@Model.Article" name="articleInjection" />
                <span asp-validation-for="Article" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Carton" class="control-label"></label>
                <input asp-for="Carton" class="form-control" />
                <input class="form-control" hidden id="cartonInjection" value="@Model.Carton" name="cartonInjection" />
                <span asp-validation-for="Carton" class="text-danger"></span>
            </div>
           
            <div class="form-group">
                <label asp-for="Palette" class="control-label"></label>
                <input asp-for="Palette" class="form-control" />
                <input class="form-control" hidden id="paletteInjection" value="@Model.Palette" name="paletteInjection" />
                <span asp-validation-for="Palette" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantite" class="control-label"></label>
                <input asp-for="Quantite" class="form-control" />
                <input class="form-control" hidden id="quantiteInjection" value="@Model.Quantite" name="quantiteInjection" />
                <span asp-validation-for="Quantite" class="text-danger"></span>
            </div>
           
             <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" hidden class="form-control" />
                <input asp-for="Date" class="form-control" disabled />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Operateur" class="control-label"></label>
                <input asp-for="Operateur" hidden class="form-control" />
                <input class="form-control" value="" id="operator" name="operator" required />
                <span asp-validation-for="Operateur" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Motif </label>
                <textarea class="form-control" cols="20" rows="2" id="motif" name="motif" required></textarea>
            </div>

            <div class="form-group">
                <input asp-for="FinPalette" hidden class="form-control" />
                <input hidden class="form-control" value="@Model.FinPalette" name="finInjection" />
                <span asp-validation-for="FinPalette" class="text-danger"></span>
            </div>
            
            <div id="buttonForm">
                <a asp-action="Index" class="btn btn-primary">Retour</a>
                <input type="submit" value="Supprimer" class="btn btn-danger" />
            </div>

            <div class="form-group">
                <input asp-for="Emplacement" hidden class="form-control" />
                <input asp-for="Delai" hidden class="form-control" />
                <input asp-for="Libelle" hidden class="form-control" />
            </div>
        </form>
    </div>
</div>

wave_application/Views/Injection/Edit.cshtml
@model wave_application.Models.Injection

@{
    ViewData["Title"] = "Modification";
}

<h1>Modification</h1>
@if (TempData["AlertMessage"] != null)
{
    <div class="alert alert-danger">
        <strong>Erreur : </strong>@TempData["AlertMessage"]
    </div>
}
<hr />
<div class="row" id="formulaireS">
    <div class="col-md-6">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Of" class="control-label"></label>
                <input asp-for="Of" class="form-control" autocomplete="off" min="0"/>
                <input class="form-control" hidden id="ofInjection" value="@Model.Of" name="ofInjection" />
                <span asp-validation-for="Of" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <label asp-for="Article" class="control-label"></label>
                <input asp-for="Article" class="form-control" min="0" />
                <input class="form-control" hidden id="articleInjection" value="@Model.Article" name="articleInjection" />
                <span asp-validation-for="Article" class="text-danger"></span>
            </div>
             <div class="form-group">
                <label asp-for="Quantite" class="control-label"></label>
                <input asp-for="Quantite" class="form-control" min="0" />
                <input class="form-control" hidden id="quantiteInjection" value="@Model.Quantite" name="quantiteInjection" />
                <span asp-validation-for="Quantite" class="text-danger"></span>
            </div>
          
            <div class="form-group">
                <label asp-for="Carton" class="control-label"></label>
                <input asp-for="Carton" class="form-control" min="0" />
                <input class="form-control" hidden id="cartonInjection" value="@Model.Carton" name="cartonInjection" />
                <span asp-validation-for="Carton" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label class="control-label">Opérateur</label>
                <input class="form-control" value="" id="operator" name="operator" required autocomplete="off" />
            </div>

            <div class="form-group">
                <label class="control-label">Motif </label>
                <textarea class="form-control" cols="20" rows="3" id="motif" name="motif" required></textarea>
            </div>

            <div class="form-check form-switch">
                <input class="form-check-input" type="checkbox" asp-for="FinPalette">
                <label asp-for="FinPalette" class="form-check-label"></label>
            </div>

            <!----------- ICI LES CHAMPS CACHES------------>
            <div class="form-group">
                <input asp-for="Operateur" class="form-control" hidden/>
                <input asp-for="Palette" class="form-control" hidden />
                <input asp-for="Emplacement" class="form-control" hidden />
                <input asp-for="Bloquer" class="form-control" hidden />
                <input asp-for="Supprimer" class="form-control" hidden />
                <input asp-for="Delai" class="form-control" hidden />
                <input asp-for="Date" class="form-control" hidden />
                <input asp-for="Libelle" class="form-control" hidden />
            </div>
            <!---------FIN DES CHAMPS CACHES------------>
           
            <div id="buttonForm">
                <a class="btn btn-primary" asp-action="Index" class="btn btn-primary">Retour</a>
                <input type="submit" value="Valider" class="btn btn-primary" />
                <input hidden class="form-control" value="@Model.FinPalette" name="finInjection" />
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

wave_application/Views/Injection/ListeFiltre.cshtml
@model IEnumerable<wave_application.Models.Injection>
@{
    ViewData["Title"] = "Index";
}
@if (TempData["AlertSuccess"] != null)
{
    <div class="alert alert-success">
        <strong>Succès : </strong>@TempData["AlertSuccess"]
    </div>
}

<h1>Historique de l'injection</h1>

<p>
    <a class="btn btn-primary" asp-action="Index">Retour</a>
    @if (Model != null && Model.Count() > 0)
    {
        <a href="@Url.Action("DownloadPdf", "Injection")"> <img src="~/img/document-pdf.svg" id="pdf" /></a>
    }
</p>
@if(Model != null && Model.Count() > 0){
    <table class="table table-bordered table-striped">
    <thead class="text-center">
        <tr>
            <th>
                N° OF
            </th>
            <th>
                N° Article
            </th>
            <th>
                Quantité
            </th>
            <th>
                N° Carton
            </th>
            <th>
                N° Palette
            </th>
            <th>
                Opérateur
            </th>

            <th>
                Date
            </th>
            <th>
                Fin Palette
            </th>
                <th>Action</th>
        </tr>
    </thead>
    <tbody class="text-center">
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Of)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Article)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Quantite)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Carton)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Palette)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Operateur)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Date)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FinPalette)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-primary">Modifier</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Supprimer</a>
                </td>
            </tr>
        }
    </tbody>
</table>
}
else
{
    <h1> La liste est vide</h1>
}

wave_application/Views/Injection/ListeModification.cshtml
@model IEnumerable<wave_application.Models.BackupInjection>

@{
    ViewData["Title"] = "ListeModification";
}

<h1>Liste des Modifications</h1>

<p>
    <a class="btn btn-primary" asp-action="Index">Retour</a>
</p>
<table class="table table-bordered table-striped">
    <thead class="text-center">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Of)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Article)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Quantite)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Carton)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FinPalette)
            </th>
            <th>
               Modifié par
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Motif)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
        </tr>
    </thead>
    <tbody class="text-center">
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Of)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Article)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Quantite)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Carton)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FinPalette)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Operateur)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Motif)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
        </tr>
}
    </tbody>
</table>
<!--  ____________________________________PAGINATION_____________________________________________ -->
<div id="paginator" class="btn-group">
    @if (ViewBag.HasPreviousPage)
    {
        <a href="@Url.Action("ListeModification", new { page = ViewBag.PageNumber - 1, pageSize = ViewBag.PageSize })" class="page-link">Précédent</a>
    }

    @if (ViewBag.PageNumber > 1)
    {
        <a href="@Url.Action("ListeModification", new { page = 1, pageSize = ViewBag.PageSize })" class="page-link">1</a>
    }

    @if (ViewBag.PageNumber > 5)
    {
        <span class="ellipsis">...</span>
    }

    @for (int i = Math.Max(1, ViewBag.PageNumber - 3); i <= Math.Min(ViewBag.PageNumber + 3, ViewBag.TotalPages); i++)
    {
        if (i != 1 && i != ViewBag.TotalPages)
        {
            if (i == ViewBag.PageNumber)
            {
                <span class="page-link current">@i</span>
            }
            else
            {
                <a href="@Url.Action("ListeModification", new { page = i, pageSize = ViewBag.PageSize })" class="page-link">@i</a>
            }
        }
    }

    @if (ViewBag.PageNumber < ViewBag.TotalPages - 4)
    {
        <span class="ellipsis">...</span>
    }

    @if (ViewBag.PageNumber < ViewBag.TotalPages)
    {
        <a href="@Url.Action("ListeModification", new { page = ViewBag.TotalPages, pageSize = ViewBag.PageSize })" class="page-link">@ViewBag.TotalPages</a>
    }

    @if (ViewBag.HasNextPage)
    {
        <a href="@Url.Action("ListeModification", new { page = ViewBag.PageNumber + 1, pageSize = ViewBag.PageSize })" class="page-link">Suivant</a>
    }
</div>

<!--  ___________________________________FIN PAGINATION_______________________________________________________________________ -->

wave_application/Views/Injection/ModalDate.cshtml
<!-- Modal -->
<div class="modal fade" id="ModalDate" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title" id="exampleModalLabel">Remplir les champs</h3>
                   
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span> 
                </button>
            </div>
           
            <div class="modal-body">
                <form method="post" action="@Url.Action("ReplaceData", "Injection")">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label class="control-label">N° OF ou Article</label>
                        <input class="form-control" name="mot"/>
                    </div>

                    <div class="form-group">
                        <label  class="control-label">Début date</label>
                        <input type="date" class="form-control" name="dateDebut"/>
                    </div>

                    <div class="form-group">
                        <label class="control-label">Fin date</label>
                        <input type="date" class="form-control" name="dateFin" />
                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer</button>
                        <input type="submit" value="Valider" class="btn btn-primary"/>
                    </div>
                </form>
            </div>

        </div>
    </div>
</div>